### PR TITLE
fix: group member duplicates

### LINKED ISSUE #65: [bug] Count de patients contradictoire dans la vue d'une cohorte existante ?
Exemple : https://demo.arkhn.com/cohort/cohort/12123/patients (se connecter en mode admin)

image

image

Le count global indique 112 patients sur la cohorte. 
Mais quand on regarde la répartition par périmètres, le tableau homme/femme/vivant/décédé, ou encore la liste des patients, on en voit 74 seulement.

Qui a raison ? 😎

### PR DESCRIPTION
**Pull request by tevariou**
## Fixes

Fixes #65 by @MiskoG

### CODE REVIEW

**Comment by MiskoG** [comment]
Bien vu le petit "group" 😄

File: src/services/cohortCreation/index.ts [hunk 1]
```diff
@@ -169,7 +169,7 @@ const createCohortGroup = async (jsonQuery: string, cohortName?: string): Promis
     name: cohortName,
     type: GroupTypeKind._person,
     actual: true,
-    quantity: patientIds.length,
+    quantity: uniq(patientIds).length,
```
Comment (Jasopaum) [inline src/services/cohortCreation/index.ts]: I didn't read the whole file yet but why are there duplicate ids in the first place?

Comment (tevariou) [reply src/services/cohortCreation/index.ts:172]: because it seems we have patients belonging to multiple organizations (a patient can have encounters in several organizations)

Comment (tevariou) [reply src/services/cohortCreation/index.ts]: sorry my diagnostic was wrong in the first place. It should be more obvious where the issue was now.

File: src/services/cohortCreation/index.ts [hunk 2]
```diff
@@ -40,9 +40,9 @@ const getPatientsFromDocuments = memoize(
   async (documentQuery: string, patientFilter: string): Promise<(string | undefined)[]> => {
     const response = await adminApiFhir.get<FHIR_API_Response<IDocumentReference>>(documentQuery)
     const documents = getApiResponseResources(response)
-    const patientIds = documents
-      ?.map((document) => last(document.subject?.reference?.split('/')))
-      .filter((patientId) => !!patientId)
+    const patientIds = uniq(
+      documents?.map((document) => last(document.subject?.reference?.split('/'))).filter((patientId) => !!patientId)
```
Comment (Jasopaum) [inline src/services/cohortCreation/index.ts]: I've already seen `.filter(Boolean)` used to do something similar. I find it easier to read, what do you think?

**Review by Jasopaum — APPROVED** [review]
